config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"


  resources :wish_lists

  root "wish_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/wish_list.rb
class WishList < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    private
    def record_not_found
        render file: "#{Rails.root}/public/404.html", status: 404, layout: false
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end

    def contact
    end
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
    
    before_action :find_wish_list, only: [:edit, :update, :destroy, :show]

    def index
        @wish_lists = WishList.all
    end

    def new
        @new_wish_list = WishList.new 
    end

    def create
        @new_wish_list = WishList.new(wish_list_params)
        if @new_wish_list.save
            flash[:notice] = "許願卡新增成功！"
            redirect_to root_path
        else
            # redirect_to new_wish_path, alert:"有欄位沒填唷"
            render :new
        end
    end

    def show 
    end

    def edit
    end

    def update
        if @wish_list.update(wish_list_params)
            redirect_to root_path, notice:"許願卡更新成功！"
        else
            render :edit
        end
    end

    def destroy
        @wish_list.destroy
        redirect_to root_path, notice:"許願卡刪除成功！"
    end

    private
    def find_wish_list
        @wish_list = WishList.find(params[:id])
    end

    def wish_list_params
        clean_params = params.require(:wish_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WishSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if flash.any? %>
    <div style="background-color: green; color:white">
      <%= flash[:notice] %>
    </div>

    <div style="background-color: red; color: white">
      <%= flash[:alert] %>
    </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello World</h1>

<a href="/contact">聯絡我們</a>
<%= link_to "關於我們", "/contact" %>
<%= link_to "關於我們", contact_path %>
<%= link_to "關於我們", contact_url %>

<a href="/">回到首頁</a>
<%= link_to "回到首頁", "/" %>
<%= link_to "關於我們", root_path %>

app/views/pages/contact.html.erb
<h1>聯絡我們</h1>

<a href="/about">關於我們</a>
<%= link_to "關於我們", "/about" %>
<%= link_to "關於我們", about_path %>
<%= link_to "關於我們", about_url %>

<a href="/">回到首頁</a>
<%= link_to "回到首頁", "/" %>
<%= link_to "關於我們", root_path %>

app/views/pages/home.html.erb
<h1>首頁</h1>

<a href="/about">關於我們</a>
<%= link_to "關於我們", "/about" %>
<%= link_to "關於我們", about_path %>  <!-- 好處改網站的網頁名稱時，可以只改一個地方整個網站都改好 -->>
<%= link_to "關於我們", about_url %>   <!-- 絕對路徑是給外部人員使用 -->

<a href="/contact">聯絡我們</a>
<%= link_to "聯絡我們", "/contact" %>
<%= link_to "關於我們", contact_path %>
<%= link_to "關於我們", contact_url %>

<%= link_to "新增願望清單", make_a_wish_path %>

app/views/wish_lists/_form.html.erb
<!-- view helper -->
<%= form_with(model: wish_list) do |form| %>
<!-- form helper -->
<div>
    <%= form.label :title%>
    <%= form.text_field :title%>
</div>

<div>
    <%= form.label :description%>
    <%= form.text_area :description %>
</div>

<div>
    <%= form.label :submit%>
    <%= form.submit%>
</div>
    
<% end %>

app/views/wish_lists/edit.html.erb
<h1>編輯願望清單</h1>

<%= render "form", wish_list: @wish_list %>

app/views/wish_lists/index.html.erb
<!-- <a data-method="delete"href="">刪除</a> -->
<h1>許願卡、清單</h1>
<%= link_to "新增許願卡", new_wish_list_path %>

<ul>
    <% @wish_lists.each do |wish_list| %>
    <li>
        <%= link_to "編輯", edit_wish_list_path(wish_list) %>
        <%= link_to "刪除", wish_list_path(wish_list), method: "delete", data: {confirm: "確定嗎？"} %>
        <%= link_to wish_list.title, wish_list_path(wish_list) %>
    </li>
    <%end%>
</ul>

app/views/wish_lists/new.html.erb
<h1>新增許願卡</h1>

<%= render "form", wish_list: @new_wish_list %>

app/views/wish_lists/show.html.erb
<section>
    <header>
        <h1><%= @wish_list.title %></h1>
    </header>

    <article>
        <%= simple_format(@wish_list.description) %>
    </article>
</section>